name: "Schema Validation"

on: [push]

jobs:
  validate-tile-jsons:
    name: Validate Tile JSONs
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Validate JSONs
        uses: walbo/validate-json@v1.1.0
        with:
          schema: data/schema.config.json
          files: data/**/sprites.json
          print-valid-files: true
